# Generated by Django 2.1.3 on 2018-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liv', '0003_auto_20181128_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualbook',
            name='key',
            field=models.ForeignKey(on_delete='SET_NULL', to='liv.BookFromLivelib'),
        ),
    ]
